name: _chapter-tests

on:
  workflow_call:
    inputs:
      chapter:
        required: true
        type: string
      py-versions:
        required: false
        type: string
        default: '["3.10","3.11","3.12"]'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.py-versions) }}

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-py${{ matrix.python-version }}-

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f "${{ inputs.chapter }}/requirements.txt" ]; then
            python -m pip install -r "${{ inputs.chapter }}/requirements.txt"
          fi
          if [ -f "${{ inputs.chapter }}/requirements_ch3.txt" ]; then
            python -m pip install -r "${{ inputs.chapter }}/requirements_ch3.txt"
          fi
          python -m pip install pytest

      - name: Run tests
        run: python -m pytest -q ${{ inputs.chapter }}/tests

