name: chapter tests (reusable)

on:
  workflow_call:
    inputs:
      chapter:
        description: "Folder name of the chapter (e.g., ch2_rl_formulation)"
        required: true
        type: string

jobs:
  test:
    name: ${{ inputs.chapter }} (py${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install dependencies (root requirements.txt)
        run: pip install -r requirements.txt

      - name: Show environment
        run: |
          python -V
          pip list

      - name: Run tests
        run: |
          echo "Running pytest in ${{ inputs.chapter }}/tests"
          pytest -q ${{ inputs.chapter }}/tests
