name: ch11
on:
  push:
    paths: ['ch11_policy_gradient/**', '.github/workflows/ch11.yml']
  pull_request:
    paths: ['ch11_policy_gradient/**', '.github/workflows/ch11.yml']
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8','3.9','3.10','3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: |
          python -m pip install -U pip
          pip install -r ch11_policy_gradient/requirements.txt
      - env:
          PYTHONPATH: .
        run: pytest -q ch11_policy_gradient/tests
