name: ch2 tests

on:
  push:
    branches: [ "main" ]
    paths:
      - "ch2_rl_formulation/**"
      - ".github/workflows/ch2.yml"
      - ".github/workflows/_chapter-tests.yml"
      - "requirements.txt"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ch2_rl_formulation/**"
      - ".github/workflows/ch2.yml"
      - ".github/workflows/_chapter-tests.yml"
      - "requirements.txt"

jobs:
  call:
    uses: ./.github/workflows/_chapter-tests.yml
    with:
      chapter: ch2_rl_formulation
