name: ch9

on:
  push:
    paths:
      - "ch9_model_based_planning/**"
      - ".github/workflows/ch9.yml"
  pull_request:
    paths:
      - "ch9_model_based_planning/**"
      - ".github/workflows/ch9.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy>=1.23 matplotlib>=3.7 pytest

      - name: Run Chapter 9 tests
        shell: bash
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE"
          python -m pytest -q ch9_model_based_planning/tests/test_ch9_mbrl.py
