# .github/workflows/python-tests.yml
name: Python (Chapters)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chapter: [ch2_rl_formulation, ch3_bandits]   # add/remove chapters as needed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Root requirements (optional)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Chapter-specific requirements (if present)
          if [ -f "${{ matrix.chapter }}/requirements.txt" ]; then \
            pip install -r "${{ matrix.chapter }}/requirements.txt"; \
          fi
          pip install pytest

      - name: Make repo importable
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Run ${{ matrix.chapter }} tests
        run: pytest -q ${{ matrix.chapter }}/tests
