jobs:
  ch2:
    uses: ./.github/workflows/_chapter-tests.yml
    with:
      chapter: ch2_rl_formulation

  ch3:
    uses: ./.github/workflows/_chapter-tests.yml
    with:
      chapter: ch3_multi_armed_bandits

  ch4:
    uses: ./.github/workflows/_chapter-tests.yml
    with:
      chapter: ch4_dynamic_programming

  ch5:
    uses: ./.github/workflows/_chapter-tests.yml
    with:
      chapter: ch5_monte_carlo

  ch6:
    uses: ./.github/workflows/_chapter-tests.yml
    with:
      chapter: ch6_td_learning

  ch7:
    uses: ./.github/workflows/_chapter-tests.yml
    with:
      chapter: ch7_td_control
