# .github/workflows/python-tests.yml
name: Python (Chapters)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chapter: [ch2_rl_formulation, ch3_bandits]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f "${{ matrix.chapter }}/requirements.txt" ]; then \
            pip install -r "${{ matrix.chapter }}/requirements.txt"; \
          fi
          pip install pytest

      - name: Make repo importable
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Check if ${{ matrix.chapter }} has tests
        id: has_tests
        run: |
          if compgen -G "${{ matrix.chapter }}/tests/**/*.py" > /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run ${{ matrix.chapter }} tests
        if: steps.has_tests.outputs.exists == 'true'
        run: pytest -q ${{ matrix.chapter }}/tests

      - name: Note skipped chapter
        if: steps.has_tests.outputs.exists != 'true'
        run: echo "No tests found for ${{ matrix.chapter }} — skipping."
